package blackjack.domain.type

enum class TrumpCard constructor(val shape: TrumpCardShape, val number: List<Int>) {
    HEART_1(TrumpCardShape.HEART, listOf(1)),
    HEART_2(TrumpCardShape.HEART, listOf(2)),
    HEART_3(TrumpCardShape.HEART, listOf(3)),
    HEART_4(TrumpCardShape.HEART, listOf(4)),
    HEART_5(TrumpCardShape.HEART, listOf(5)),
    HEART_6(TrumpCardShape.HEART, listOf(6)),
    HEART_7(TrumpCardShape.HEART, listOf(7)),
    HEART_8(TrumpCardShape.HEART, listOf(9)),
    HEART_9(TrumpCardShape.HEART, listOf(9)),
    HEART_10(TrumpCardShape.HEART, listOf(10)),
    HEART_ACE(TrumpCardShape.HEART, listOf(1, 11)),
    HEART_QUEEN(TrumpCardShape.HEART, listOf(10)),
    HEART_JACK(TrumpCardShape.HEART, listOf(10)),
    HEART_KING(TrumpCardShape.HEART, listOf(10)),
    DIAMOND_1(TrumpCardShape.DIAMOND, listOf(1)),
    DIAMOND_2(TrumpCardShape.DIAMOND, listOf(2)),
    DIAMOND_3(TrumpCardShape.DIAMOND, listOf(3)),
    DIAMOND_4(TrumpCardShape.DIAMOND, listOf(4)),
    DIAMOND_5(TrumpCardShape.DIAMOND, listOf(5)),
    DIAMOND_6(TrumpCardShape.DIAMOND, listOf(6)),
    DIAMOND_7(TrumpCardShape.DIAMOND, listOf(7)),
    DIAMOND_8(TrumpCardShape.DIAMOND, listOf(9)),
    DIAMOND_9(TrumpCardShape.DIAMOND, listOf(9)),
    DIAMOND_10(TrumpCardShape.DIAMOND, listOf(10)),
    DIAMOND_ACE(TrumpCardShape.DIAMOND, listOf(1, 11)),
    DIAMOND_QUEEN(TrumpCardShape.DIAMOND, listOf(10)),
    DIAMOND_JACK(TrumpCardShape.DIAMOND, listOf(10)),
    DIAMOND_KING(TrumpCardShape.DIAMOND, listOf(10)),
    SPADE_1(TrumpCardShape.SPADE, listOf(1)),
    SPADE_2(TrumpCardShape.SPADE, listOf(2)),
    SPADE_3(TrumpCardShape.SPADE, listOf(3)),
    SPADE_4(TrumpCardShape.SPADE, listOf(4)),
    SPADE_5(TrumpCardShape.SPADE, listOf(5)),
    SPADE_6(TrumpCardShape.SPADE, listOf(6)),
    SPADE_7(TrumpCardShape.SPADE, listOf(7)),
    SPADE_8(TrumpCardShape.SPADE, listOf(9)),
    SPADE_9(TrumpCardShape.SPADE, listOf(9)),
    SPADE_10(TrumpCardShape.SPADE, listOf(10)),
    SPADE_ACE(TrumpCardShape.SPADE, listOf(1, 11)),
    SPADE_QUEEN(TrumpCardShape.SPADE, listOf(10)),
    SPADE_JACK(TrumpCardShape.SPADE, listOf(10)),
    SPADE_KING(TrumpCardShape.SPADE, listOf(10)),
    CLUB_1(TrumpCardShape.ClUB, listOf(1)),
    CLUB_2(TrumpCardShape.ClUB, listOf(2)),
    CLUB_3(TrumpCardShape.ClUB, listOf(3)),
    CLUB_4(TrumpCardShape.ClUB, listOf(4)),
    CLUB_5(TrumpCardShape.ClUB, listOf(5)),
    CLUB_6(TrumpCardShape.ClUB, listOf(6)),
    CLUB_7(TrumpCardShape.ClUB, listOf(7)),
    CLUB_8(TrumpCardShape.ClUB, listOf(9)),
    CLUB_9(TrumpCardShape.ClUB, listOf(9)),
    CLUB_10(TrumpCardShape.ClUB, listOf(10)),
    CLUB_ACE(TrumpCardShape.ClUB, listOf(1, 11)),
    CLUB_QUEEN(TrumpCardShape.ClUB, listOf(10)),
    CLUB_JACK(TrumpCardShape.ClUB, listOf(10)),
    CLUB_KING(TrumpCardShape.ClUB, listOf(10)),
}
